name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 列出检出的文件（调试）
      run: ls -R

    - name: 设置 JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: 赋予 gradlew 可执行权限
      run: chmod +x gradlew

    - name: 使用 Gradle 构建
      run: ./gradlew build

